<?php
$sources = [
    "GlypeX",
    "Lion_MTProto",
    "ProxyMTProto",
    "Myporoxy",
    "iMTProto",
    "TelMTProto",
    "PlusMTProto",
    "MTP_roto",
    "ProxyHagh",
    "proxyhubs",
    "ProxyDaemi",
    "proxyme",
    "ProxyMTProto_tel",
    "proxyy",
    "russian_proxy",
    "PinkProxy",
    "V2rayng_Fast",
    "daorzadannet",
    "v2rayNGNeT",
    "PAINB0Y",
    "proxy_kafee",
    "alephproxy",
    "YekoyekVpn",
    "ProxyForOpeta"
];

?>
